name: Nuget Package Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Build with dotnet
        run: dotnet build --configuration Release NRig.sln
      - name: Test with dotnet
        run: dotnet test NRig.sln
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack NRig package
        run: dotnet pack --configuration Release NRig.sln
      - name: Push NRig package to nuget
        run: dotnet nuget push **/nrig.*.nupkg
              --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
              --source https://api.nuget.org/v3/index.json
              --skip-duplicate
              -n 1
      - name: Pack NRig.Hamlib package
        run: dotnet pack --configuration Release NRig.Hamlib
      - name: Push NRig.Hamlib package to nuget
        run: dotnet nuget push **/nrig.hamlib.*.nupkg
              --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
              --source https://api.nuget.org/v3/index.json
              --skip-duplicate
              -n 1